spring:
  redis:
    # Redis数据库索引（默认为0）
   database: 0
    # Redis服务器地址
   host: localhost
    # Redis服务器连接端口
   port: 6379
   timeout: 300   jedis:      pool:        max-idle: 8
        max-active: 8
        max-wait: -1     
  #Druid
  datasource:
   type: com.alibaba.druid.pool.DruidDataSource 
   url: jdbc:mysql://127.0.0.1:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
   username: root
   password: 852025
   driver-class-name: com.mysql.cj.jdbc.Driver
   initialization-mode: never  
   druid:
      initial-size: 10
      max-active: 100
      time-between-eviction-runs-millis: 60000
      max-wait: 60000
   #pagehelper     data:
    mongodb:
      host: localhost
      port: 27017
      database: springbootblog
    elasticsearch:
      repositories:
        enabled: true
   
  
          
#date format    
  jackson:    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8  
  #文件上传  
      servlet:    multipart:      enabled: true
      max-file-size: 10MB #限制单文件最大大小
pagehelper:
  helper-dialect: mysql
  reasonable: true
  page-size-zero: true
  support-methods-arguments: true
  params: count=countSql
  #jwt
jwt:
  secret: blog
  expiration: 7200000
  tokenHeader: Authorization
  #minio
minio:
  endpoint: http://127.0.0.1:9000 #MinIO服务所在地址
  bucketName: blog #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
  #log
logging:  level:    com.zyd.blog.mapper: trace  